import { beforeEach, describe, expect, it, vi } from "vitest";

const { execFileSyncMock, getStagedDiffMock } = vi.hoisted(() => ({
  execFileSyncMock: vi.fn(),
  getStagedDiffMock: vi.fn(),
}));

vi.mock("node:child_process", () => ({
  execFileSync: execFileSyncMock,
}));

vi.mock("./git-operations.js", () => ({
  getStagedDiff: getStagedDiffMock,
}));

import { generateCommitMessage } from "./git-assist.js";

describe("generateCommitMessage", () => {
  beforeEach(() => {
    execFileSyncMock.mockReset();
    getStagedDiffMock.mockReset();
    getStagedDiffMock.mockReturnValue("diff --git a/a.txt b/a.txt\n");
  });

  it("uses claude CLI for claude sessions", () => {
    execFileSyncMock.mockReturnValue("feat: generated message\n");

    const message = generateCommitMessage({
      provider: "claude",
      projectPath: "/tmp/project",
      model: "claude-sonnet-4-6",
    });

    expect(message).toBe("feat: generated message");
    expect(execFileSyncMock).toHaveBeenCalledWith(
      "claude",
      [
        "-p",
        "--model",
        "claude-sonnet-4-6",
        "Write a single Conventional Commits message in English for the staged changes below. Output only the commit message, with no quotes or explanation.",
      ],
      expect.objectContaining({
        cwd: "/tmp/project",
        input: "diff --git a/a.txt b/a.txt",
        encoding: "utf-8",
        maxBuffer: 1024 * 1024,
      }),
    );
  });

  it("uses codex CLI for codex sessions", () => {
    execFileSyncMock.mockReturnValue("fix: generated by codex\n");

    const message = generateCommitMessage({
      provider: "codex",
      projectPath: "/tmp/project",
      model: "gpt-5.4",
    });

    expect(message).toBe("fix: generated by codex");
    expect(execFileSyncMock).toHaveBeenCalledWith(
      "codex",
      [
        "-q",
        "--model",
        "gpt-5.4",
        "Write a single Conventional Commits message in English for the staged changes below. Output only the commit message, with no quotes or explanation.",
      ],
      expect.objectContaining({
        cwd: "/tmp/project",
        input: "diff --git a/a.txt b/a.txt",
        encoding: "utf-8",
        maxBuffer: 1024 * 1024,
      }),
    );
  });

  it("fails when no files are staged", () => {
    getStagedDiffMock.mockReturnValue("");

    expect(() =>
      generateCommitMessage({
        provider: "claude",
        projectPath: "/tmp/project",
      }),
    ).toThrow(/Nothing to commit/);
  });

  it("fails when CLI returns empty output", () => {
    execFileSyncMock.mockReturnValue(" \n");

    expect(() =>
      generateCommitMessage({
        provider: "claude",
        projectPath: "/tmp/project",
      }),
    ).toThrow(/empty output/);
  });
});
